-- SDKWork music consolidated initialization baseline (sqlite)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/sqlite/0001_music_legacy_baseline.sql
-- Consolidated legacy baseline for sdkwork-music database module.
-- source: crates/sdkwork-music-storage-sqlx-rust/migrations/0001_music_foundation.sql

CREATE TABLE music_artist (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  bio TEXT,
  avatar_media_resource_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);

CREATE TABLE music_album (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  artist_id TEXT NOT NULL REFERENCES music_artist(id),
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  cover_media_resource_id TEXT,
  release_date TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);

CREATE TABLE music_audio_asset (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  title TEXT NOT NULL,
  drive_space_id TEXT NOT NULL,
  drive_node_id TEXT NOT NULL,
  drive_uri TEXT NOT NULL,
  media_resource_id TEXT,
  media_resource_snapshot TEXT,
  mime_type TEXT NOT NULL,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  checksum_algorithm TEXT,
  checksum_value TEXT,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, drive_uri)
);

CREATE TABLE music_track (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  artist_id TEXT NOT NULL REFERENCES music_artist(id),
  album_id TEXT REFERENCES music_album(id),
  audio_asset_id TEXT REFERENCES music_audio_asset(id),
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  track_number INTEGER,
  published_at TEXT,
  archived_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);

CREATE TABLE music_track_tag (
  track_id TEXT NOT NULL REFERENCES music_track(id) ON DELETE CASCADE,
  tag TEXT NOT NULL,
  PRIMARY KEY (track_id, tag)
);

CREATE TABLE music_lyric (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  track_id TEXT NOT NULL REFERENCES music_track(id) ON DELETE CASCADE,
  language TEXT NOT NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, track_id, language, source)
);

CREATE TABLE music_lyric_line (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  lyric_id TEXT NOT NULL REFERENCES music_lyric(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  start_ms INTEGER,
  end_ms INTEGER,
  text TEXT NOT NULL,
  romanized_text TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (lyric_id, position)
);

CREATE TABLE music_rights_policy (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  policy_code TEXT NOT NULL,
  title TEXT NOT NULL,
  license_type TEXT NOT NULL,
  usage_scope TEXT NOT NULL,
  attribution_required INTEGER NOT NULL DEFAULT 0,
  commercial_use_allowed INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, policy_code)
);

CREATE TABLE music_playlist (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);

CREATE TABLE music_playlist_track (
  playlist_id TEXT NOT NULL REFERENCES music_playlist(id) ON DELETE CASCADE,
  track_id TEXT NOT NULL REFERENCES music_track(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  PRIMARY KEY (playlist_id, track_id)
);

CREATE TABLE music_playlist_follow (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  playlist_id TEXT NOT NULL REFERENCES music_playlist(id) ON DELETE CASCADE,
  source TEXT,
  created_at TEXT NOT NULL,
  UNIQUE (tenant_id, user_id, playlist_id)
);

CREATE TABLE music_playlist_collaborator (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  playlist_id TEXT NOT NULL REFERENCES music_playlist(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  role TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, playlist_id, user_id)
);

CREATE TABLE music_comment (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  parent_comment_id TEXT REFERENCES music_comment(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  moderation_status TEXT NOT NULL,
  like_count INTEGER NOT NULL DEFAULT 0,
  reply_count INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE music_content_report (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  reporter_user_id TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  reason_code TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL,
  resolved_by TEXT,
  resolution_note TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  resolved_at TEXT
);

CREATE TABLE music_chart (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  chart_type TEXT NOT NULL,
  status TEXT NOT NULL,
  period_start TEXT,
  period_end TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);

CREATE TABLE music_chart_entry (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  chart_id TEXT NOT NULL REFERENCES music_chart(id) ON DELETE CASCADE,
  track_id TEXT NOT NULL REFERENCES music_track(id) ON DELETE CASCADE,
  rank INTEGER NOT NULL,
  previous_rank INTEGER,
  score INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (chart_id, track_id),
  UNIQUE (chart_id, rank)
);

CREATE TABLE music_recommendation_shelf (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  shelf_type TEXT NOT NULL,
  algorithm_code TEXT,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);

CREATE TABLE music_recommendation_item (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  shelf_id TEXT NOT NULL REFERENCES music_recommendation_shelf(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL,
  item_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  reason_code TEXT,
  score INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (shelf_id, position),
  UNIQUE (shelf_id, item_type, item_id)
);

CREATE TABLE music_recommendation_feedback (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  item_type TEXT NOT NULL,
  item_id TEXT NOT NULL,
  feedback_type TEXT NOT NULL,
  reason_code TEXT,
  context_json TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE music_user_library_item (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  item_type TEXT NOT NULL,
  item_id TEXT NOT NULL,
  source TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, user_id, item_type, item_id)
);

CREATE TABLE music_like (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  item_type TEXT NOT NULL,
  item_id TEXT NOT NULL,
  reaction_type TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (tenant_id, user_id, item_type, item_id, reaction_type)
);

CREATE TABLE music_follow (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (tenant_id, user_id, target_type, target_id)
);

CREATE TABLE music_listening_history (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT,
  track_id TEXT NOT NULL REFERENCES music_track(id) ON DELETE CASCADE,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  played_seconds INTEGER NOT NULL DEFAULT 0,
  completion_rate INTEGER NOT NULL DEFAULT 0,
  source TEXT,
  occurred_at TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE music_download_entitlement (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  track_id TEXT NOT NULL REFERENCES music_track(id) ON DELETE CASCADE,
  audio_asset_id TEXT NOT NULL REFERENCES music_audio_asset(id),
  quality TEXT NOT NULL,
  status TEXT NOT NULL,
  expires_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, user_id, track_id, quality)
);

CREATE TABLE music_playback_session (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  device_id TEXT NOT NULL,
  current_track_id TEXT REFERENCES music_track(id) ON DELETE SET NULL,
  queue_json TEXT,
  position_ms INTEGER NOT NULL DEFAULT 0,
  playback_state TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, user_id, device_id)
);

CREATE TABLE music_search_index (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  keywords TEXT,
  tags_json TEXT,
  popularity_score INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, resource_type, resource_id)
);

CREATE TABLE music_search_suggestion (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  suggestion_type TEXT NOT NULL,
  display_text TEXT NOT NULL,
  query_text TEXT NOT NULL,
  weight INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, suggestion_type, query_text)
);

CREATE TABLE music_ai_generation_project (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  visibility TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE music_ai_style_preset (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  style_tags_json TEXT NOT NULL,
  prompt_hint TEXT,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);

CREATE TABLE music_ai_prompt_template (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  template_text TEXT NOT NULL,
  variables_json TEXT,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, slug)
);

CREATE TABLE music_ai_generation_provider (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  provider_code TEXT NOT NULL,
  display_name TEXT NOT NULL,
  provider_family TEXT NOT NULL,
  capability TEXT NOT NULL,
  invocation_mode TEXT NOT NULL,
  claw_router_provider_code TEXT NOT NULL,
  claw_router_endpoint_key TEXT NOT NULL,
  claw_router_standard_path TEXT NOT NULL,
  supports_polling INTEGER NOT NULL DEFAULT 0,
  supports_webhook INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  config_snapshot TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, provider_code)
);

CREATE TABLE music_ai_generation_provider_model (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  provider_id TEXT NOT NULL REFERENCES music_ai_generation_provider(id) ON DELETE CASCADE,
  provider_code TEXT NOT NULL,
  model_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  capability TEXT NOT NULL,
  min_duration_seconds INTEGER NOT NULL DEFAULT 0,
  max_duration_seconds INTEGER NOT NULL DEFAULT 0,
  max_variant_count INTEGER NOT NULL DEFAULT 1,
  supported_formats_json TEXT NOT NULL,
  supported_style_tags_json TEXT NOT NULL,
  pricing_unit TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, provider_code, model_name)
);

CREATE TABLE music_ai_generation_task (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  project_id TEXT REFERENCES music_ai_generation_project(id) ON DELETE SET NULL,
  user_id TEXT NOT NULL,
  prompt TEXT NOT NULL,
  lyrics_prompt TEXT,
  style_tags_json TEXT NOT NULL,
  model_provider TEXT NOT NULL,
  model_name TEXT NOT NULL,
  generation_mode TEXT NOT NULL DEFAULT 'text_to_music',
  provider_code TEXT,
  provider_model TEXT,
  provider_invocation_mode TEXT NOT NULL DEFAULT 'async_task',
  external_task_id TEXT,
  provider_status TEXT,
  provider_output_count INTEGER NOT NULL DEFAULT 0,
  idempotency_key TEXT,
  request_hash TEXT,
  last_provider_sync_at TEXT,
  next_poll_at TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0,
  reference_drive_uri TEXT,
  status TEXT NOT NULL,
  moderation_status TEXT NOT NULL,
  rights_policy_id TEXT REFERENCES music_rights_policy(id),
  error_message TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  completed_at TEXT
);

CREATE TABLE music_ai_generation_provider_attempt (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  task_id TEXT NOT NULL REFERENCES music_ai_generation_task(id) ON DELETE CASCADE,
  provider_id TEXT NOT NULL REFERENCES music_ai_generation_provider(id),
  provider_code TEXT NOT NULL,
  model_name TEXT NOT NULL,
  invocation_mode TEXT NOT NULL,
  claw_router_endpoint_key TEXT NOT NULL,
  claw_router_standard_path TEXT NOT NULL,
  claw_router_operation_id TEXT NOT NULL,
  claw_router_request_id TEXT,
  external_task_id TEXT,
  status TEXT NOT NULL,
  provider_status TEXT,
  request_snapshot TEXT,
  response_snapshot TEXT,
  submitted_at TEXT,
  last_polled_at TEXT,
  completed_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE music_ai_generation_provider_event (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  task_id TEXT NOT NULL REFERENCES music_ai_generation_task(id) ON DELETE CASCADE,
  attempt_id TEXT REFERENCES music_ai_generation_provider_attempt(id) ON DELETE SET NULL,
  provider_code TEXT NOT NULL,
  external_task_id TEXT,
  external_event_id TEXT,
  event_type TEXT NOT NULL,
  source TEXT NOT NULL,
  provider_status TEXT NOT NULL,
  status_before TEXT NOT NULL,
  status_after TEXT NOT NULL,
  payload_hash TEXT NOT NULL,
  payload_snapshot TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (provider_code, external_event_id),
  UNIQUE (provider_code, external_task_id, event_type, payload_hash)
);

CREATE TABLE music_ai_generation_variant (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  task_id TEXT NOT NULL REFERENCES music_ai_generation_task(id) ON DELETE CASCADE,
  audio_asset_id TEXT REFERENCES music_audio_asset(id),
  title TEXT NOT NULL,
  drive_uri TEXT NOT NULL,
  media_resource_snapshot TEXT,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  moderation_status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE music_ai_generation_credit_ledger (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  task_id TEXT REFERENCES music_ai_generation_task(id) ON DELETE SET NULL,
  direction TEXT NOT NULL,
  amount INTEGER NOT NULL,
  balance_after INTEGER NOT NULL,
  reason_code TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE music_ai_generation_notification (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  task_id TEXT NOT NULL REFERENCES music_ai_generation_task(id) ON DELETE CASCADE,
  notification_type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  read_at TEXT,
  UNIQUE (tenant_id, user_id, task_id, notification_type)
);

CREATE TABLE music_moderation_signal (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  signal_type TEXT NOT NULL,
  severity TEXT NOT NULL,
  status TEXT NOT NULL,
  reason TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE music_release (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  track_id TEXT REFERENCES music_track(id) ON DELETE SET NULL,
  source_type TEXT NOT NULL,
  source_id TEXT NOT NULL,
  rights_policy_id TEXT REFERENCES music_rights_policy(id),
  status TEXT NOT NULL,
  published_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE music_release_channel (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  release_id TEXT NOT NULL,
  channel_code TEXT NOT NULL,
  distribution_status TEXT NOT NULL,
  scheduled_at TEXT,
  published_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, release_id, channel_code)
);

CREATE TABLE music_rights_territory (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  rights_policy_id TEXT NOT NULL,
  region_code TEXT NOT NULL,
  availability TEXT NOT NULL,
  starts_at TEXT,
  ends_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (tenant_id, rights_policy_id, region_code)
);

CREATE TABLE music_play_event (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  track_id TEXT NOT NULL REFERENCES music_track(id) ON DELETE CASCADE,
  user_id TEXT,
  occurred_at TEXT NOT NULL
);

CREATE TABLE music_editorial_audit (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  action TEXT NOT NULL,
  actor_user_id TEXT,
  before_json TEXT,
  after_json TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE music_schema_version (
  sequence INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  checksum TEXT NOT NULL,
  applied_at TEXT NOT NULL
);

CREATE TABLE music_migration_lock (
  lock_name TEXT PRIMARY KEY,
  lock_owner TEXT NOT NULL,
  locked_until TEXT NOT NULL,
  heartbeat_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX idx_music_artist_tenant_slug ON music_artist (tenant_id, slug);
CREATE INDEX idx_music_album_tenant_artist ON music_album (tenant_id, artist_id, release_date);
CREATE INDEX idx_music_audio_asset_tenant_status ON music_audio_asset (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_track_tenant_status_updated ON music_track (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_track_tenant_artist ON music_track (tenant_id, artist_id, status);
CREATE INDEX idx_music_track_tenant_album ON music_track (tenant_id, album_id, status);
CREATE INDEX idx_music_track_tag_tag ON music_track_tag (tag, track_id);
CREATE INDEX idx_music_lyric_track_language ON music_lyric (tenant_id, track_id, language);
CREATE INDEX idx_music_lyric_line_position ON music_lyric_line (lyric_id, position);
CREATE INDEX idx_music_rights_policy_tenant_status ON music_rights_policy (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_playlist_tenant_slug ON music_playlist (tenant_id, slug);
CREATE INDEX idx_music_playlist_track_position ON music_playlist_track (playlist_id, position);
CREATE INDEX idx_music_playlist_follow_user ON music_playlist_follow (tenant_id, user_id, created_at DESC);
CREATE INDEX idx_music_playlist_collaborator_playlist ON music_playlist_collaborator (tenant_id, playlist_id, status);
CREATE INDEX idx_music_comment_resource_created ON music_comment (tenant_id, resource_type, resource_id, created_at DESC);
CREATE INDEX idx_music_content_report_status_created ON music_content_report (tenant_id, status, created_at DESC);
CREATE INDEX idx_music_chart_tenant_status_updated ON music_chart (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_chart_entry_chart_rank ON music_chart_entry (chart_id, rank);
CREATE INDEX idx_music_recommendation_shelf_tenant_status ON music_recommendation_shelf (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_recommendation_item_shelf_position ON music_recommendation_item (shelf_id, position);
CREATE INDEX idx_music_recommendation_feedback_user_created ON music_recommendation_feedback (tenant_id, user_id, created_at DESC);
CREATE INDEX idx_music_user_library_user_updated ON music_user_library_item (tenant_id, user_id, updated_at DESC);
CREATE INDEX idx_music_like_user_item ON music_like (tenant_id, user_id, item_type, item_id);
CREATE INDEX idx_music_follow_user_target ON music_follow (tenant_id, user_id, target_type, target_id);
CREATE INDEX idx_music_listening_history_user_track ON music_listening_history (tenant_id, user_id, track_id, occurred_at DESC);
CREATE INDEX idx_music_listening_history_track ON music_listening_history (tenant_id, track_id, occurred_at DESC);
CREATE INDEX idx_music_download_entitlement_user_status ON music_download_entitlement (tenant_id, user_id, status, updated_at DESC);
CREATE INDEX idx_music_playback_session_user_status ON music_playback_session (tenant_id, user_id, playback_state, updated_at DESC);
CREATE INDEX idx_music_search_index_query ON music_search_index (tenant_id, resource_type, popularity_score DESC, updated_at DESC);
CREATE INDEX idx_music_search_suggestion_tenant_type ON music_search_suggestion (tenant_id, suggestion_type, status, weight DESC);
CREATE INDEX idx_music_ai_generation_project_user_updated ON music_ai_generation_project (tenant_id, user_id, updated_at DESC);
CREATE INDEX idx_music_ai_style_preset_tenant_status ON music_ai_style_preset (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_ai_prompt_template_tenant_status ON music_ai_prompt_template (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_ai_generation_provider_tenant_status ON music_ai_generation_provider (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_ai_generation_provider_model_tenant_status ON music_ai_generation_provider_model (tenant_id, provider_code, status, updated_at DESC);
CREATE INDEX idx_music_ai_generation_task_tenant_status_updated ON music_ai_generation_task (tenant_id, status, updated_at DESC);
CREATE INDEX idx_music_ai_generation_task_user_updated ON music_ai_generation_task (tenant_id, user_id, updated_at DESC);
CREATE INDEX idx_music_ai_generation_task_provider_external ON music_ai_generation_task (tenant_id, provider_code, external_task_id);
CREATE INDEX idx_music_ai_generation_provider_attempt_task ON music_ai_generation_provider_attempt (tenant_id, task_id, created_at DESC);
CREATE INDEX idx_music_ai_generation_provider_event_task_created ON music_ai_generation_provider_event (tenant_id, task_id, created_at DESC);
CREATE INDEX idx_music_ai_generation_variant_task ON music_ai_generation_variant (task_id, created_at DESC);
CREATE INDEX idx_music_ai_generation_credit_ledger_user_created ON music_ai_generation_credit_ledger (tenant_id, user_id, created_at DESC);
CREATE INDEX idx_music_ai_generation_notification_user_status ON music_ai_generation_notification (tenant_id, user_id, status, created_at DESC);
CREATE INDEX idx_music_moderation_signal_resource ON music_moderation_signal (tenant_id, resource_type, resource_id, created_at DESC);
CREATE INDEX idx_music_release_tenant_status_published ON music_release (tenant_id, status, published_at DESC);
CREATE INDEX idx_music_release_channel_release_status ON music_release_channel (tenant_id, release_id, distribution_status);
CREATE INDEX idx_music_rights_territory_policy_region ON music_rights_territory (tenant_id, rights_policy_id, region_code);
CREATE INDEX idx_music_play_event_track ON music_play_event (tenant_id, track_id, occurred_at DESC);
CREATE INDEX idx_music_editorial_audit_resource ON music_editorial_audit (tenant_id, resource_type, resource_id, created_at DESC);
